// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

    #include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Arc2;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label2;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
void ui_event_Label1( lv_event_t * e);
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui____initial_actions0;

LV_FONT_DECLARE( ui_font_Font20);
LV_FONT_DECLARE( ui_font_FontHan20);
LV_FONT_DECLARE( ui_font_Font1);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
